### PR TITLE
PHP Syntax error related to the PHP version

### PR DESCRIPTION
**Pull request by croxarens**
Hi,

Installing and compiling your module I got the following error:
```
PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in vendor/clearpay/module-clearpay/Model/ExpressPayment/ShippingListProvider.php on line 14
```
Below is the problematic line:
```
class ShippingListProvider
{
 ->   private \Magento\Checkout\Api\TotalsInformationManagementInterface $totalsInformationManagement;

```
The problem is related to the PHP syntax, as the typed properties are only allowed since PHP 7.4, but in the composer.json there is no reference about the PHP version, that's why I was able to install it.

Looking at [your documentation](https://developers.clearpay.co.uk/clearpay-online/docs/magento-2-getting-started) I see your module is compatible with Magento version 2.3.5-p1 or greater, which has a PHP minimum requirement of PHP 7.1.

In the pull request, I've:

- added the PHP version requirements in Composer, so that if the PHP version is not correct, Composer and IDE like PHPStorm flag it
- Update the PHP syntax on the problematic file to reflect PHP 7.1 standards

### CODE REVIEW

**Comment by chickenland** [comment]
Just to add https://github.com/clearpayeu/clearpay-magento-2/blob/master/Controller/Payment/Express.php#L66 has the same issue.

**Comment by croxarens** [comment]
@chickenland I've updated the syntax in that file too.
@clearpayplugins any chance to have the request approved and merged?

**Comment by clearpayplugins** [comment]
Thanks @croxarens and @chickenland, 
The issue has been addressed and published.

**Comment by clearpayplugins** [comment]
Thank you for your valuable contribution.
Closing the PR as the issue has been already addressed and published.

Thank you

**Pull request closed without merging**
